/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var shared_pb = require('./shared_pb.js');
goog.exportSymbol('proto.fontbakery.dashboard.FamilyJob', null, global);
goog.exportSymbol('proto.fontbakery.dashboard.FamilyJob.DistributedInfo', null, global);
goog.exportSymbol('proto.fontbakery.dashboard.FamilyJob.JobType', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fontbakery.dashboard.FamilyJob = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.fontbakery.dashboard.FamilyJob.repeatedFields_, null);
};
goog.inherits(proto.fontbakery.dashboard.FamilyJob, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.fontbakery.dashboard.FamilyJob.displayName = 'proto.fontbakery.dashboard.FamilyJob';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.fontbakery.dashboard.FamilyJob.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.fontbakery.dashboard.FamilyJob.prototype.toObject = function(opt_includeInstance) {
  return proto.fontbakery.dashboard.FamilyJob.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fontbakery.dashboard.FamilyJob} msg The msg instance to transform.
 * @return {!Object}
 */
proto.fontbakery.dashboard.FamilyJob.toObject = function(includeInstance, msg) {
  var f, obj = {
    docid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    filesList: jspb.Message.toObjectList(msg.getFilesList(),
    shared_pb.File.toObject, includeInstance),
    type: jspb.Message.getFieldWithDefault(msg, 3, 0),
    distributedinfo: (f = msg.getDistributedinfo()) && proto.fontbakery.dashboard.FamilyJob.DistributedInfo.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fontbakery.dashboard.FamilyJob}
 */
proto.fontbakery.dashboard.FamilyJob.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.fontbakery.dashboard.FamilyJob;
  return proto.fontbakery.dashboard.FamilyJob.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fontbakery.dashboard.FamilyJob} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fontbakery.dashboard.FamilyJob}
 */
proto.fontbakery.dashboard.FamilyJob.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setDocid(value);
      break;
    case 2:
      var value = new shared_pb.File;
      reader.readMessage(value,shared_pb.File.deserializeBinaryFromReader);
      msg.addFiles(value);
      break;
    case 3:
      var value = /** @type {!proto.fontbakery.dashboard.FamilyJob.JobType} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 4:
      var value = new proto.fontbakery.dashboard.FamilyJob.DistributedInfo;
      reader.readMessage(value,proto.fontbakery.dashboard.FamilyJob.DistributedInfo.deserializeBinaryFromReader);
      msg.setDistributedinfo(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fontbakery.dashboard.FamilyJob.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.fontbakery.dashboard.FamilyJob.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fontbakery.dashboard.FamilyJob} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.fontbakery.dashboard.FamilyJob.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDocid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getFilesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      shared_pb.File.serializeBinaryToWriter
    );
  }
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getDistributedinfo();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.fontbakery.dashboard.FamilyJob.DistributedInfo.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.fontbakery.dashboard.FamilyJob.JobType = {
  DRAGANDDROP_ORIGIN: 0,
  DRAGANDDROP_DISTRIBUTED: 1
};


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fontbakery.dashboard.FamilyJob.DistributedInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.fontbakery.dashboard.FamilyJob.DistributedInfo.repeatedFields_, null);
};
goog.inherits(proto.fontbakery.dashboard.FamilyJob.DistributedInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.fontbakery.dashboard.FamilyJob.DistributedInfo.displayName = 'proto.fontbakery.dashboard.FamilyJob.DistributedInfo';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.fontbakery.dashboard.FamilyJob.DistributedInfo.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.fontbakery.dashboard.FamilyJob.DistributedInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.fontbakery.dashboard.FamilyJob.DistributedInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fontbakery.dashboard.FamilyJob.DistributedInfo} msg The msg instance to transform.
 * @return {!Object}
 */
proto.fontbakery.dashboard.FamilyJob.DistributedInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    orderList: jspb.Message.getField(msg, 2)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fontbakery.dashboard.FamilyJob.DistributedInfo}
 */
proto.fontbakery.dashboard.FamilyJob.DistributedInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.fontbakery.dashboard.FamilyJob.DistributedInfo;
  return proto.fontbakery.dashboard.FamilyJob.DistributedInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fontbakery.dashboard.FamilyJob.DistributedInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fontbakery.dashboard.FamilyJob.DistributedInfo}
 */
proto.fontbakery.dashboard.FamilyJob.DistributedInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addOrder(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fontbakery.dashboard.FamilyJob.DistributedInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.fontbakery.dashboard.FamilyJob.DistributedInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fontbakery.dashboard.FamilyJob.DistributedInfo} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.fontbakery.dashboard.FamilyJob.DistributedInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getOrderList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
};


/**
 * optional int32 id = 1;
 * @return {number}
 */
proto.fontbakery.dashboard.FamilyJob.DistributedInfo.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.fontbakery.dashboard.FamilyJob.DistributedInfo.prototype.setId = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * repeated string order = 2;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<string>}
 */
proto.fontbakery.dashboard.FamilyJob.DistributedInfo.prototype.getOrderList = function() {
  return /** @type {!Array.<string>} */ (jspb.Message.getField(this, 2));
};


/** @param {!Array.<string>} value */
proto.fontbakery.dashboard.FamilyJob.DistributedInfo.prototype.setOrderList = function(value) {
  jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.fontbakery.dashboard.FamilyJob.DistributedInfo.prototype.addOrder = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


proto.fontbakery.dashboard.FamilyJob.DistributedInfo.prototype.clearOrderList = function() {
  this.setOrderList([]);
};


/**
 * optional string docid = 1;
 * @return {string}
 */
proto.fontbakery.dashboard.FamilyJob.prototype.getDocid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.fontbakery.dashboard.FamilyJob.prototype.setDocid = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * repeated File files = 2;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.fontbakery.dashboard.File>}
 */
proto.fontbakery.dashboard.FamilyJob.prototype.getFilesList = function() {
  return /** @type{!Array.<!proto.fontbakery.dashboard.File>} */ (
    jspb.Message.getRepeatedWrapperField(this, shared_pb.File, 2));
};


/** @param {!Array.<!proto.fontbakery.dashboard.File>} value */
proto.fontbakery.dashboard.FamilyJob.prototype.setFilesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.fontbakery.dashboard.File=} opt_value
 * @param {number=} opt_index
 * @return {!proto.fontbakery.dashboard.File}
 */
proto.fontbakery.dashboard.FamilyJob.prototype.addFiles = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.fontbakery.dashboard.File, opt_index);
};


proto.fontbakery.dashboard.FamilyJob.prototype.clearFilesList = function() {
  this.setFilesList([]);
};


/**
 * optional JobType type = 3;
 * @return {!proto.fontbakery.dashboard.FamilyJob.JobType}
 */
proto.fontbakery.dashboard.FamilyJob.prototype.getType = function() {
  return /** @type {!proto.fontbakery.dashboard.FamilyJob.JobType} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {!proto.fontbakery.dashboard.FamilyJob.JobType} value */
proto.fontbakery.dashboard.FamilyJob.prototype.setType = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional DistributedInfo distributedInfo = 4;
 * @return {?proto.fontbakery.dashboard.FamilyJob.DistributedInfo}
 */
proto.fontbakery.dashboard.FamilyJob.prototype.getDistributedinfo = function() {
  return /** @type{?proto.fontbakery.dashboard.FamilyJob.DistributedInfo} */ (
    jspb.Message.getWrapperField(this, proto.fontbakery.dashboard.FamilyJob.DistributedInfo, 4));
};


/** @param {?proto.fontbakery.dashboard.FamilyJob.DistributedInfo|undefined} value */
proto.fontbakery.dashboard.FamilyJob.prototype.setDistributedinfo = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.fontbakery.dashboard.FamilyJob.prototype.clearDistributedinfo = function() {
  this.setDistributedinfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.fontbakery.dashboard.FamilyJob.prototype.hasDistributedinfo = function() {
  return jspb.Message.getField(this, 4) != null;
};


goog.object.extend(exports, proto.fontbakery.dashboard);
