/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var shared_pb = require('./shared_pb.js');
goog.exportSymbol('proto.fontbakery.dashboard.CacheItem', null, global);
goog.exportSymbol('proto.fontbakery.dashboard.CacheKey', null, global);
goog.exportSymbol('proto.fontbakery.dashboard.CacheStatus', null, global);
goog.exportSymbol('proto.fontbakery.dashboard.FamilyJob', null, global);
goog.exportSymbol('proto.fontbakery.dashboard.FamilyJob.DistributedInfo', null, global);
goog.exportSymbol('proto.fontbakery.dashboard.FamilyJob.JobType', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fontbakery.dashboard.FamilyJob = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.fontbakery.dashboard.FamilyJob.repeatedFields_, null);
};
goog.inherits(proto.fontbakery.dashboard.FamilyJob, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.fontbakery.dashboard.FamilyJob.displayName = 'proto.fontbakery.dashboard.FamilyJob';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.fontbakery.dashboard.FamilyJob.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.fontbakery.dashboard.FamilyJob.prototype.toObject = function(opt_includeInstance) {
  return proto.fontbakery.dashboard.FamilyJob.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fontbakery.dashboard.FamilyJob} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fontbakery.dashboard.FamilyJob.toObject = function(includeInstance, msg) {
  var f, obj = {
    docid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    filesList: jspb.Message.toObjectList(msg.getFilesList(),
    shared_pb.File.toObject, includeInstance),
    type: jspb.Message.getFieldWithDefault(msg, 3, 0),
    distributedinfo: (f = msg.getDistributedinfo()) && proto.fontbakery.dashboard.FamilyJob.DistributedInfo.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fontbakery.dashboard.FamilyJob}
 */
proto.fontbakery.dashboard.FamilyJob.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.fontbakery.dashboard.FamilyJob;
  return proto.fontbakery.dashboard.FamilyJob.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fontbakery.dashboard.FamilyJob} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fontbakery.dashboard.FamilyJob}
 */
proto.fontbakery.dashboard.FamilyJob.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setDocid(value);
      break;
    case 2:
      var value = new shared_pb.File;
      reader.readMessage(value,shared_pb.File.deserializeBinaryFromReader);
      msg.addFiles(value);
      break;
    case 3:
      var value = /** @type {!proto.fontbakery.dashboard.FamilyJob.JobType} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 4:
      var value = new proto.fontbakery.dashboard.FamilyJob.DistributedInfo;
      reader.readMessage(value,proto.fontbakery.dashboard.FamilyJob.DistributedInfo.deserializeBinaryFromReader);
      msg.setDistributedinfo(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fontbakery.dashboard.FamilyJob.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.fontbakery.dashboard.FamilyJob.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fontbakery.dashboard.FamilyJob} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fontbakery.dashboard.FamilyJob.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDocid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getFilesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      shared_pb.File.serializeBinaryToWriter
    );
  }
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getDistributedinfo();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.fontbakery.dashboard.FamilyJob.DistributedInfo.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.fontbakery.dashboard.FamilyJob.JobType = {
  UNKNOWN: 0,
  DRAGANDDROP_ORIGIN: 1,
  DRAGANDDROP_DISTRIBUTED: 2
};


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fontbakery.dashboard.FamilyJob.DistributedInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.fontbakery.dashboard.FamilyJob.DistributedInfo.repeatedFields_, null);
};
goog.inherits(proto.fontbakery.dashboard.FamilyJob.DistributedInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.fontbakery.dashboard.FamilyJob.DistributedInfo.displayName = 'proto.fontbakery.dashboard.FamilyJob.DistributedInfo';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.fontbakery.dashboard.FamilyJob.DistributedInfo.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.fontbakery.dashboard.FamilyJob.DistributedInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.fontbakery.dashboard.FamilyJob.DistributedInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fontbakery.dashboard.FamilyJob.DistributedInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fontbakery.dashboard.FamilyJob.DistributedInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    orderList: jspb.Message.getRepeatedField(msg, 2)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fontbakery.dashboard.FamilyJob.DistributedInfo}
 */
proto.fontbakery.dashboard.FamilyJob.DistributedInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.fontbakery.dashboard.FamilyJob.DistributedInfo;
  return proto.fontbakery.dashboard.FamilyJob.DistributedInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fontbakery.dashboard.FamilyJob.DistributedInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fontbakery.dashboard.FamilyJob.DistributedInfo}
 */
proto.fontbakery.dashboard.FamilyJob.DistributedInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addOrder(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fontbakery.dashboard.FamilyJob.DistributedInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.fontbakery.dashboard.FamilyJob.DistributedInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fontbakery.dashboard.FamilyJob.DistributedInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fontbakery.dashboard.FamilyJob.DistributedInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getOrderList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
};


/**
 * optional int32 id = 1;
 * @return {number}
 */
proto.fontbakery.dashboard.FamilyJob.DistributedInfo.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.fontbakery.dashboard.FamilyJob.DistributedInfo.prototype.setId = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * repeated string order = 2;
 * @return {!Array.<string>}
 */
proto.fontbakery.dashboard.FamilyJob.DistributedInfo.prototype.getOrderList = function() {
  return /** @type {!Array.<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/** @param {!Array.<string>} value */
proto.fontbakery.dashboard.FamilyJob.DistributedInfo.prototype.setOrderList = function(value) {
  jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.fontbakery.dashboard.FamilyJob.DistributedInfo.prototype.addOrder = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


proto.fontbakery.dashboard.FamilyJob.DistributedInfo.prototype.clearOrderList = function() {
  this.setOrderList([]);
};


/**
 * optional string docid = 1;
 * @return {string}
 */
proto.fontbakery.dashboard.FamilyJob.prototype.getDocid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.fontbakery.dashboard.FamilyJob.prototype.setDocid = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * repeated File files = 2;
 * @return {!Array.<!proto.fontbakery.dashboard.File>}
 */
proto.fontbakery.dashboard.FamilyJob.prototype.getFilesList = function() {
  return /** @type{!Array.<!proto.fontbakery.dashboard.File>} */ (
    jspb.Message.getRepeatedWrapperField(this, shared_pb.File, 2));
};


/** @param {!Array.<!proto.fontbakery.dashboard.File>} value */
proto.fontbakery.dashboard.FamilyJob.prototype.setFilesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.fontbakery.dashboard.File=} opt_value
 * @param {number=} opt_index
 * @return {!proto.fontbakery.dashboard.File}
 */
proto.fontbakery.dashboard.FamilyJob.prototype.addFiles = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.fontbakery.dashboard.File, opt_index);
};


proto.fontbakery.dashboard.FamilyJob.prototype.clearFilesList = function() {
  this.setFilesList([]);
};


/**
 * optional JobType type = 3;
 * @return {!proto.fontbakery.dashboard.FamilyJob.JobType}
 */
proto.fontbakery.dashboard.FamilyJob.prototype.getType = function() {
  return /** @type {!proto.fontbakery.dashboard.FamilyJob.JobType} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {!proto.fontbakery.dashboard.FamilyJob.JobType} value */
proto.fontbakery.dashboard.FamilyJob.prototype.setType = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional DistributedInfo distributedInfo = 4;
 * @return {?proto.fontbakery.dashboard.FamilyJob.DistributedInfo}
 */
proto.fontbakery.dashboard.FamilyJob.prototype.getDistributedinfo = function() {
  return /** @type{?proto.fontbakery.dashboard.FamilyJob.DistributedInfo} */ (
    jspb.Message.getWrapperField(this, proto.fontbakery.dashboard.FamilyJob.DistributedInfo, 4));
};


/** @param {?proto.fontbakery.dashboard.FamilyJob.DistributedInfo|undefined} value */
proto.fontbakery.dashboard.FamilyJob.prototype.setDistributedinfo = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.fontbakery.dashboard.FamilyJob.prototype.clearDistributedinfo = function() {
  this.setDistributedinfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.fontbakery.dashboard.FamilyJob.prototype.hasDistributedinfo = function() {
  return jspb.Message.getField(this, 4) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fontbakery.dashboard.CacheItem = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.fontbakery.dashboard.CacheItem, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.fontbakery.dashboard.CacheItem.displayName = 'proto.fontbakery.dashboard.CacheItem';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.fontbakery.dashboard.CacheItem.prototype.toObject = function(opt_includeInstance) {
  return proto.fontbakery.dashboard.CacheItem.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fontbakery.dashboard.CacheItem} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fontbakery.dashboard.CacheItem.toObject = function(includeInstance, msg) {
  var f, obj = {
    payload: (f = msg.getPayload()) && shared_pb.Files.toObject(includeInstance, f),
    clientid: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fontbakery.dashboard.CacheItem}
 */
proto.fontbakery.dashboard.CacheItem.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.fontbakery.dashboard.CacheItem;
  return proto.fontbakery.dashboard.CacheItem.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fontbakery.dashboard.CacheItem} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fontbakery.dashboard.CacheItem}
 */
proto.fontbakery.dashboard.CacheItem.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new shared_pb.Files;
      reader.readMessage(value,shared_pb.Files.deserializeBinaryFromReader);
      msg.setPayload(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setClientid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fontbakery.dashboard.CacheItem.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.fontbakery.dashboard.CacheItem.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fontbakery.dashboard.CacheItem} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fontbakery.dashboard.CacheItem.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPayload();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      shared_pb.Files.serializeBinaryToWriter
    );
  }
  f = message.getClientid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional Files payload = 1;
 * @return {?proto.fontbakery.dashboard.Files}
 */
proto.fontbakery.dashboard.CacheItem.prototype.getPayload = function() {
  return /** @type{?proto.fontbakery.dashboard.Files} */ (
    jspb.Message.getWrapperField(this, shared_pb.Files, 1));
};


/** @param {?proto.fontbakery.dashboard.Files|undefined} value */
proto.fontbakery.dashboard.CacheItem.prototype.setPayload = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.fontbakery.dashboard.CacheItem.prototype.clearPayload = function() {
  this.setPayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.fontbakery.dashboard.CacheItem.prototype.hasPayload = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string clientid = 2;
 * @return {string}
 */
proto.fontbakery.dashboard.CacheItem.prototype.getClientid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.fontbakery.dashboard.CacheItem.prototype.setClientid = function(value) {
  jspb.Message.setField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fontbakery.dashboard.CacheKey = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.fontbakery.dashboard.CacheKey, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.fontbakery.dashboard.CacheKey.displayName = 'proto.fontbakery.dashboard.CacheKey';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.fontbakery.dashboard.CacheKey.prototype.toObject = function(opt_includeInstance) {
  return proto.fontbakery.dashboard.CacheKey.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fontbakery.dashboard.CacheKey} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fontbakery.dashboard.CacheKey.toObject = function(includeInstance, msg) {
  var f, obj = {
    key: jspb.Message.getFieldWithDefault(msg, 1, ""),
    clientid: jspb.Message.getFieldWithDefault(msg, 2, ""),
    force: jspb.Message.getFieldWithDefault(msg, 3, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fontbakery.dashboard.CacheKey}
 */
proto.fontbakery.dashboard.CacheKey.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.fontbakery.dashboard.CacheKey;
  return proto.fontbakery.dashboard.CacheKey.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fontbakery.dashboard.CacheKey} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fontbakery.dashboard.CacheKey}
 */
proto.fontbakery.dashboard.CacheKey.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setKey(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setClientid(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setForce(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fontbakery.dashboard.CacheKey.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.fontbakery.dashboard.CacheKey.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fontbakery.dashboard.CacheKey} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fontbakery.dashboard.CacheKey.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getKey();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getClientid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getForce();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
};


/**
 * optional string key = 1;
 * @return {string}
 */
proto.fontbakery.dashboard.CacheKey.prototype.getKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.fontbakery.dashboard.CacheKey.prototype.setKey = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string clientid = 2;
 * @return {string}
 */
proto.fontbakery.dashboard.CacheKey.prototype.getClientid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.fontbakery.dashboard.CacheKey.prototype.setClientid = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional bool force = 3;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.fontbakery.dashboard.CacheKey.prototype.getForce = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 3, false));
};


/** @param {boolean} value */
proto.fontbakery.dashboard.CacheKey.prototype.setForce = function(value) {
  jspb.Message.setField(this, 3, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fontbakery.dashboard.CacheStatus = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.fontbakery.dashboard.CacheStatus, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.fontbakery.dashboard.CacheStatus.displayName = 'proto.fontbakery.dashboard.CacheStatus';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.fontbakery.dashboard.CacheStatus.prototype.toObject = function(opt_includeInstance) {
  return proto.fontbakery.dashboard.CacheStatus.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fontbakery.dashboard.CacheStatus} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fontbakery.dashboard.CacheStatus.toObject = function(includeInstance, msg) {
  var f, obj = {
    key: jspb.Message.getFieldWithDefault(msg, 1, ""),
    instances: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fontbakery.dashboard.CacheStatus}
 */
proto.fontbakery.dashboard.CacheStatus.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.fontbakery.dashboard.CacheStatus;
  return proto.fontbakery.dashboard.CacheStatus.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fontbakery.dashboard.CacheStatus} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fontbakery.dashboard.CacheStatus}
 */
proto.fontbakery.dashboard.CacheStatus.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setKey(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setInstances(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fontbakery.dashboard.CacheStatus.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.fontbakery.dashboard.CacheStatus.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fontbakery.dashboard.CacheStatus} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fontbakery.dashboard.CacheStatus.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getKey();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getInstances();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
};


/**
 * optional string key = 1;
 * @return {string}
 */
proto.fontbakery.dashboard.CacheStatus.prototype.getKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.fontbakery.dashboard.CacheStatus.prototype.setKey = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional int32 instances = 2;
 * @return {number}
 */
proto.fontbakery.dashboard.CacheStatus.prototype.getInstances = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.fontbakery.dashboard.CacheStatus.prototype.setInstances = function(value) {
  jspb.Message.setField(this, 2, value);
};


goog.object.extend(exports, proto.fontbakery.dashboard);
