apiVersion: apps/v1
kind: Deployment
metadata:
  name: fontbakery-manifest-main
spec:
  replicas: 1
  selector:
    matchLabels:
      component: fontbakery-manifest-main
  template:
    metadata:
      labels:
        component: fontbakery-manifest-main
        role: manifest
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      containers:
      - name: fontbakery-manifest-main
        image: gcr.io/fontbakery-168509/base-javascript:20
        env:
          - name: FONTBAKERY_LOG_LEVEL
            value: "DEBUG"
          - name: RETHINKDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: external-resources
                key: rethinkdb-password
        workingDir: /var/javascript
        command: ["node", "node/ManifestMain.js"]
