apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: rabbitmq
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      component: rabbitmq
  template:
    metadata:
      labels:
        app: taskQueue
        component: rabbitmq
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      containers:
      - image: rabbitmq:3-management
        name: rabbitmq
        ports:
        - containerPort: 5672
        env:
          - name: RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS
            value: "-rabbit heartbeat 1200"
        resources:
          limits:
            cpu: 1
            memory: 2048Mi
          requests:
            cpu: .5
            memory: 1024Mi
# Setting these must be reflected in the clients!
#        env:
#        - name: RABBITMQ_DEFAULT_USER
#          value: "admin"
#        - name: RABBITMQ_DEFAULT_PASS
#          value: "admin"
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-management
  labels:
    component: rabbitmq
spec:
  ports:
    - port: 8888
      targetPort: 15672
      name: http
  selector:
    component: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  labels:
    component: rabbitmq
spec:
  ports:
  - port: 5672
  selector:
    app: taskQueue
    component: rabbitmq
