apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: fontbakery-github-operations
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: fontbakery-github-operations
    spec:
      containers:
      - name: fontbakery-github-operations
        image: gcr.io/fontbakery-168509/base-javascript:13
        env:
          - name: FONTBAKERY_LOG_LEVEL
            value: "DEBUG"
          - name: GITHUB_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: external-resources
                key: github-api-token
        ports:
        - containerPort: 50051
        workingDir: /var/javascript
        command: ["node", "node/GitHubOperationsServer.js", "-p", "50051"]
---
apiVersion: v1
kind: Service
metadata:
  name: fontbakery-github-operations
  labels:
    component: fontbakery-github-operations
spec:
  ports:
    - port: 50051
      targetPort: 50051
  selector:
    component: fontbakery-github-operations
