apiVersion: apps/v1
kind: Deployment
metadata:
  name: fontbakery-api
spec:
  replicas: 1
  selector:
    matchLabels:
      run: fontbakery-api
  template:
    metadata:
      labels:
        run: fontbakery-api
    spec:
      containers:
      - name: fontbakery-api
        image: fontbakery/base-javascript:1
        env:
          - name: FONTBAKERY_LOG_LEVEL
            value: "DEBUG"
          - name: WEB_SERVER_COOKIE_SECRET
            valueFrom:
              secretKeyRef:
                name: external-resources
                key: web-server-cookie-secret
          - name: RETHINKDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: external-resources
                key: rethinkdb-password
        ports:
        - containerPort: 3000
        # NOT IN PRODUCTION
        - containerPort: 9229
        workingDir: /var/javascript
        # **NEVER** DO THIS IN PRODUCTION!
        # alias kf="kubectl -n fontbakery"
        # kf get pods
        # kf port-forward fontbakery-api-12334-123 9229:9229
        # open chrome and go to chrome://inspect
        command: ["node", "--inspect=0.0.0.0:9229", "node/api.js"]
        # PRODUCTION:
        # command: ["npm", "start"]
---
apiVersion: v1
kind: Service
metadata:
  name: fontbakery-api
  labels:
    run: fontbakery-api
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    run: fontbakery-api
