apiVersion: apps/v1
kind: Deployment
metadata:
  name: fontbakery-dispatcher
spec:
  replicas: 1
  selector:
    matchLabels:
      component: fontbakery-dispatcher
  template:
    metadata:
      labels:
        component: fontbakery-dispatcher
    spec:
      containers:
      - name: fontbakery-dispatcher
        image: fontbakery/base-javascript:1
        env:
          - name: FONTBAKERY_LOG_LEVEL
            value: "DEBUG"
          - name: FRONTEND_BASE_URL
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: frontend-base-url
          - name: DISPATCHER_MANAGER_SECRET
            valueFrom:
              secretKeyRef:
                name: external-resources
                key: dispatcher-manager-secret
          - name: RETHINKDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: external-resources
                key: rethinkdb-password
        ports:
        - containerPort: 50051
        workingDir: /var/javascript
        # command: ["node", "node/dispatcher/DispatcherProcessManager.js", "-p", "50051"]
        #  kf port-forward fontbakery-dispatcher-12334-123 9229:9229
        command: ["node", "--inspect=0.0.0.0:9229", "node/dispatcher/DispatcherProcessManager.js", "-p", "50051"]
      # depends directly on rabbitmq/amqp
      # wait until rabbitmq can be reached before starting the actual container
      initContainers:
        - name: init-wait-for-rabbitmq
          image: busybox
          command:
          - sh
          - "-c"
          - >
            until wget -q -O -
            http://guest:guest@$RABBITMQ_MANAGEMENT_SERVICE_HOST:$RABBITMQ_MANAGEMENT_SERVICE_PORT/api/aliveness-test/%2F;
            do echo [`date`] waiting for rabbitmq: 10s;
            sleep 10;
            done;
---
apiVersion: v1
kind: Service
metadata:
  name: fontbakery-dispatcher
  labels:
    component: fontbakery-dispatcher
spec:
  ports:
    - port: 50051
      targetPort: 50051
  selector:
    component: fontbakery-dispatcher
