apiVersion: apps/v1
kind: Deployment
metadata:
  name: fontbakery-manifest-githubgf
spec:
  replicas: 1
  selector:
    matchLabels:
      component: fontbakery-manifest-githubgf
  template:
    metadata:
      labels:
        component: fontbakery-manifest-githubgf
        role: manifest
    spec:
      containers:
      - name: fontbakery-manifest-githubgf
        image: fontbakery/base-javascript:1
        env:
          - name: FONTBAKERY_LOG_LEVEL
            value: "DEBUG"
          - name: DEVEL_FAMILY_WHITELIST
            value: "[\"ABeeZee\", \"Indie Flower\", \"Slabo\", \"Rosario\", \"Amiri\", \"Pacifico\", \"Astloch\"]"
          - name: GITHUB_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: external-resources
                key: github-api-token
        workingDir: /var/javascript
        #command: ["node", "node/manifestSources/Git.js", "-p", "50051"]
        command: ["node", "--inspect=0.0.0.0:9229", "node/manifestSources/Git.js", "-p", "50051"]
      # depends directly on rabbitmq/amqp
      # wait until rabbitmq can be reached before starting the actual container
      initContainers:
        - name: init-wait-for-rabbitmq
          image: busybox
          command:
          - sh
          - "-c"
          - >
            until wget -q -O -
            http://guest:guest@$RABBITMQ_MANAGEMENT_SERVICE_HOST:$RABBITMQ_MANAGEMENT_SERVICE_PORT/api/aliveness-test/%2F;
            do echo [`date`] waiting for rabbitmq: 10s;
            sleep 10;
            done;
---
apiVersion: v1
kind: Service
metadata:
  name: fontbakery-manifest-githubgf
  labels:
    component: fontbakery-manifest-githubgf
spec:
  ports:
    - port: 50051
      targetPort: 50051
  selector:
    component: fontbakery-manifest-githubgf
    role: manifest
