apiVersion: apps/v1
kind: Deployment
metadata:
  name: fontbakery-manifest-csvupstream
spec:
  replicas: 1
  selector:
    matchLabels:
      component: fontbakery-manifest-csvupstream
  template:
    metadata:
      labels:
        component: fontbakery-manifest-csvupstream
        role: manifest
    spec:
      containers:
      - name: fontbakery-manifest-csvupstream
        image: fontbakery/base-javascript:1
        env:
          - name: FONTBAKERY_LOG_LEVEL
            value: "DEBUG"
          - name: DEVEL_FAMILY_WHITELIST
            value: "[\"ABeeZee\", \"Indie Flower\", \"Slabo\", \"Rosario\", \"Amiri\", \"Pacifico\", \"Astloch\"]"
        workingDir: /var/javascript
        #command: ["node", "node/manifestSources/CSVSpreadsheet.js", "-p", "50051"]
        command: ["node", "--inspect=0.0.0.0:9229", "node/manifestSources/CSVSpreadsheet.js", "-p", "50051"]

---
apiVersion: v1
kind: Service
metadata:
  name: fontbakery-manifest-csvupstream
  labels:
    component: fontbakery-manifest-csvupstream
spec:
  ports:
    - port: 50051
      targetPort: 50051
  selector:
    component: fontbakery-manifest-csvupstream
    role: manifest
