apiVersion: apps/v1
kind: Deployment
metadata:
  name: fontbakery-manifest-master
spec:
  replicas: 1
  selector:
    matchLabels:
      component: fontbakery-manifest-master
  template:
    metadata:
      labels:
        component: fontbakery-manifest-master
        role: manifest
    spec:
      containers:
      - name: fontbakery-manifest-master
        image: fontbakery/base-javascript:1
        env:
          - name: FONTBAKERY_LOG_LEVEL
            value: "DEBUG"
          - name: RETHINKDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: external-resources
                key: rethinkdb-password
        workingDir: /var/javascript
        command: ["node", "node/ManifestMaster.js"]
