# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import shared_pb2 as shared__pb2

from shared_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages.proto',
  package='fontbakery.dashboard',
  syntax='proto3',
  serialized_pb=_b('\n\x0emessages.proto\x12\x14\x66ontbakery.dashboard\x1a\x0cshared.proto\"\xb4\x02\n\tFamilyJob\x12\r\n\x05\x64ocid\x18\x01 \x01(\t\x12)\n\x05\x66iles\x18\x02 \x03(\x0b\x32\x1a.fontbakery.dashboard.File\x12\x35\n\x04type\x18\x03 \x01(\x0e\x32\'.fontbakery.dashboard.FamilyJob.JobType\x12H\n\x0f\x64istributedInfo\x18\x04 \x01(\x0b\x32/.fontbakery.dashboard.FamilyJob.DistributedInfo\x1a,\n\x0f\x44istributedInfo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05order\x18\x02 \x03(\t\">\n\x07JobType\x12\x16\n\x12\x44RAGANDDROP_ORIGIN\x10\x00\x12\x1b\n\x17\x44RAGANDDROP_DISTRIBUTED\x10\x01P\x00\x62\x06proto3')
  ,
  dependencies=[shared__pb2.DESCRIPTOR,],
  public_dependencies=[shared__pb2.DESCRIPTOR,])



_FAMILYJOB_JOBTYPE = _descriptor.EnumDescriptor(
  name='JobType',
  full_name='fontbakery.dashboard.FamilyJob.JobType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DRAGANDDROP_ORIGIN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DRAGANDDROP_DISTRIBUTED', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=301,
  serialized_end=363,
)
_sym_db.RegisterEnumDescriptor(_FAMILYJOB_JOBTYPE)


_FAMILYJOB_DISTRIBUTEDINFO = _descriptor.Descriptor(
  name='DistributedInfo',
  full_name='fontbakery.dashboard.FamilyJob.DistributedInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='fontbakery.dashboard.FamilyJob.DistributedInfo.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='order', full_name='fontbakery.dashboard.FamilyJob.DistributedInfo.order', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=255,
  serialized_end=299,
)

_FAMILYJOB = _descriptor.Descriptor(
  name='FamilyJob',
  full_name='fontbakery.dashboard.FamilyJob',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='docid', full_name='fontbakery.dashboard.FamilyJob.docid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='files', full_name='fontbakery.dashboard.FamilyJob.files', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='fontbakery.dashboard.FamilyJob.type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='distributedInfo', full_name='fontbakery.dashboard.FamilyJob.distributedInfo', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_FAMILYJOB_DISTRIBUTEDINFO, ],
  enum_types=[
    _FAMILYJOB_JOBTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=363,
)

_FAMILYJOB_DISTRIBUTEDINFO.containing_type = _FAMILYJOB
_FAMILYJOB.fields_by_name['files'].message_type = shared__pb2._FILE
_FAMILYJOB.fields_by_name['type'].enum_type = _FAMILYJOB_JOBTYPE
_FAMILYJOB.fields_by_name['distributedInfo'].message_type = _FAMILYJOB_DISTRIBUTEDINFO
_FAMILYJOB_JOBTYPE.containing_type = _FAMILYJOB
DESCRIPTOR.message_types_by_name['FamilyJob'] = _FAMILYJOB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FamilyJob = _reflection.GeneratedProtocolMessageType('FamilyJob', (_message.Message,), dict(

  DistributedInfo = _reflection.GeneratedProtocolMessageType('DistributedInfo', (_message.Message,), dict(
    DESCRIPTOR = _FAMILYJOB_DISTRIBUTEDINFO,
    __module__ = 'messages_pb2'
    # @@protoc_insertion_point(class_scope:fontbakery.dashboard.FamilyJob.DistributedInfo)
    ))
  ,
  DESCRIPTOR = _FAMILYJOB,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:fontbakery.dashboard.FamilyJob)
  ))
_sym_db.RegisterMessage(FamilyJob)
_sym_db.RegisterMessage(FamilyJob.DistributedInfo)


# @@protoc_insertion_point(module_scope)
