# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
import messages_pb2 as messages__pb2


class CacheStub(object):
  """The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Put = channel.stream_stream(
        '/fontbakery.dashboard.Cache/Put',
        request_serializer=messages__pb2.CacheItem.SerializeToString,
        response_deserializer=messages__pb2.CacheKey.FromString,
        )
    self.Get = channel.unary_unary(
        '/fontbakery.dashboard.Cache/Get',
        request_serializer=messages__pb2.CacheKey.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_any__pb2.Any.FromString,
        )
    self.Purge = channel.unary_unary(
        '/fontbakery.dashboard.Cache/Purge',
        request_serializer=messages__pb2.CacheKey.SerializeToString,
        response_deserializer=messages__pb2.CacheStatus.FromString,
        )


class CacheServicer(object):
  """The greeting service definition.
  """

  def Put(self, request_iterator, context):
    """Sends a greeting
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Get(self, request, context):
    """Sends another greeting
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Purge(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CacheServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Put': grpc.stream_stream_rpc_method_handler(
          servicer.Put,
          request_deserializer=messages__pb2.CacheItem.FromString,
          response_serializer=messages__pb2.CacheKey.SerializeToString,
      ),
      'Get': grpc.unary_unary_rpc_method_handler(
          servicer.Get,
          request_deserializer=messages__pb2.CacheKey.FromString,
          response_serializer=google_dot_protobuf_dot_any__pb2.Any.SerializeToString,
      ),
      'Purge': grpc.unary_unary_rpc_method_handler(
          servicer.Purge,
          request_deserializer=messages__pb2.CacheKey.FromString,
          response_serializer=messages__pb2.CacheStatus.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'fontbakery.dashboard.Cache', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
