# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='shared.proto',
  package='fontbakery.dashboard',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cshared.proto\x12\x14\x66ontbakery.dashboard\"\"\n\x04\x46ile\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"2\n\x05\x46iles\x12)\n\x05\x66iles\x18\x01 \x03(\x0b\x32\x1a.fontbakery.dashboard.Fileb\x06proto3')
)




_FILE = _descriptor.Descriptor(
  name='File',
  full_name='fontbakery.dashboard.File',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='fontbakery.dashboard.File.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='fontbakery.dashboard.File.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=72,
)


_FILES = _descriptor.Descriptor(
  name='Files',
  full_name='fontbakery.dashboard.Files',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='files', full_name='fontbakery.dashboard.Files.files', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=124,
)

_FILES.fields_by_name['files'].message_type = _FILE
DESCRIPTOR.message_types_by_name['File'] = _FILE
DESCRIPTOR.message_types_by_name['Files'] = _FILES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

File = _reflection.GeneratedProtocolMessageType('File', (_message.Message,), dict(
  DESCRIPTOR = _FILE,
  __module__ = 'shared_pb2'
  # @@protoc_insertion_point(class_scope:fontbakery.dashboard.File)
  ))
_sym_db.RegisterMessage(File)

Files = _reflection.GeneratedProtocolMessageType('Files', (_message.Message,), dict(
  DESCRIPTOR = _FILES,
  __module__ = 'shared_pb2'
  # @@protoc_insertion_point(class_scope:fontbakery.dashboard.Files)
  ))
_sym_db.RegisterMessage(Files)


# @@protoc_insertion_point(module_scope)
